title: MOO-XOO GmbH
email: office@moo-xoo.com
description: 'Creating simplicity in your business'
url: 'https://moo-xoo.github.io'

# Permalinks
permalink: pretty

# Server
source: "."
destination: ./_gh_pages
encoding: UTF-8
exclude:
  - .git
  - .github
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-multiple-languages-plugin

languages: ["en", "de"]
baseurl: ""

# Custom variables
current_version: 0.1
repo: "https://github.com/moo-xoo/moo-xoo.github.io"
